name: nonogram
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  audioplayers: 
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  nonogram_dart: ^2.1.3
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/puzzles/
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"

